package:
  name: graphistry-dev
  version: "0.25.2"

source:
  git_rev: 0.25.2
  git_url: https://github.com/graphistry/pygraphistry

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - packaging>=20.1
    - typing-extensions
    - numpy
    - pandas>=0.17.0
    - protobuf>=2.6.0
    - pyarrow>=0.15.0
    - requests

test:
  requires:
    - flake8
    - mock
    - mypy
    - pytest
    - pandas-stubs
    - types-requests

about:
  home: https://www.graphistry.com/
  license: BSD
  summary: Visual Graph Analytics library for Python
  description: |
    Graphistry is a visual graph analytics library for extracting, transforming, 
    displaying, and sharing big graphs with end-to-end GPU acceleration
  doc_url: https://www.graphistry.com/docs
  dev_url: https://github.com/graphistry/pygraphistry

extra:
  author: The Graphistry Team
  author_email: pygraphistry@graphistry.com