package:
  name: graphistry-dev
  version: "0.25.2"

source:
  path: ./

requirements:
  host:
    - python
    - setuptools
  run:
    - graphistry_dev.graphistry_core
    - graphistry_dev.graphistry-umap
    - graphistry_dev.graphistry-ai

test:
  requires:
    - flake8
    - mock
    - mypy
    - pytest
    - pandas-stubs
    - types-requests

outputs:
  - name: graphistry_dev.graphistry_core
    requirements:
      - packaging>=20.1
      - typing-extensions
      - numpy
      - pandas>=0.17.0
      - protobuf>=2.6.0
      - pyarrow>=0.15.0
      - requests
  - name: graphistry_dev.graphistry-umap
    requirements:
      - umap-learn
      - dirty_cat
  - name: graphistry_dev.graphistry-ai
    requirements:
      - scikit-learn
      - scipy
      - umap-learn
      - dirty_cat
      - dgl
      - pytorch
      - sentence-transformers
      
      
about:
  home: https://www.graphistry.com/
  license: BSD
  summary: Visual Graph Analytics library for Python
  description: |
    Graphistry is a visual graph analytics library for extracting, transforming, 
    displaying, and sharing big graphs with end-to-end GPU acceleration
  doc_url: https://www.graphistry.com/docs
  dev_url: https://github.com/graphistry/pygraphistry

extra:
  author: The Graphistry Team
  author_email: pygraphistry@graphistry.com


