name: Publish Python 🐍 distributions 📦 to Conda

on:
  release:
    types: [published]


jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to Conda
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
        with:  # fetch tag for versioneer
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pypa/build
        run: >-
          python -m pip install -e .[build]

      - name: Build a binary wheel and a source tarball
        run: >-
          ./bin/build.sh


      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYGGRAPHISTRY_PYPI }}